SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `ZJ_USER_PROFILE` (
  `ID` varchar(32) NOT NULL,
  `USER_ID` varchar(32) NOT NULL,
  `IDENTITY_STATUS` varchar(32) NOT NULL DEFAULT 'UNVERIFIED',
  `REAL_NAME` varchar(64) DEFAULT NULL,
  `ID_CARD_CIPHERTEXT` varchar(512) DEFAULT NULL,
  `IDENTITY_FRONT_URL` varchar(512) DEFAULT NULL,
  `IDENTITY_BACK_URL` varchar(512) DEFAULT NULL,
  `REVIEW_REMARK` varchar(500) DEFAULT NULL,
  `DELETE_FLAG` varchar(32) DEFAULT NULL,
  `CREATE_TIME` datetime DEFAULT NULL,
  `CREATE_USER` varchar(32) DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(32) DEFAULT NULL,
  PRIMARY KEY (`ID`), UNIQUE KEY `UK_ZJ_PROFILE_USER` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='租迹用户业务资料';

CREATE TABLE IF NOT EXISTS `ZJ_LISTING` (
  `ID` varchar(32) NOT NULL,
  `PUBLISHER_ID` varchar(32) NOT NULL,
  `TITLE` varchar(120) NOT NULL,
  `CITY` varchar(40) NOT NULL,
  `DISTRICT` varchar(40) NOT NULL,
  `COMMUNITY` varchar(120) NOT NULL,
  `MONTHLY_RENT_CENTS` bigint NOT NULL,
  `AVAILABLE_FROM` date NOT NULL,
  `LEASE_ENDS_AT` date NOT NULL,
  `DESCRIPTION` text,
  `STATUS` varchar(32) NOT NULL DEFAULT 'PENDING_REVIEW',
  `REVIEW_REMARK` varchar(500) DEFAULT NULL,
  `EXPOSURE_SCORE` int NOT NULL DEFAULT 0,
  `DELETE_FLAG` varchar(32) DEFAULT NULL,
  `CREATE_TIME` datetime DEFAULT NULL,
  `CREATE_USER` varchar(32) DEFAULT NULL,
  `UPDATE_TIME` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(32) DEFAULT NULL,
  PRIMARY KEY (`ID`), KEY `IDX_ZJ_LISTING_CITY_STATUS` (`CITY`,`STATUS`),
  KEY `IDX_ZJ_LISTING_PUBLISHER` (`PUBLISHER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='转租房源';

CREATE TABLE IF NOT EXISTS `ZJ_LISTING_IMAGE` (
  `ID` varchar(32) NOT NULL, `LISTING_ID` varchar(32) NOT NULL,
  `FILE_URL` varchar(512) NOT NULL, `SORT_CODE` int NOT NULL DEFAULT 0,
  `DELETE_FLAG` varchar(32) DEFAULT NULL, `CREATE_TIME` datetime DEFAULT NULL,
  `CREATE_USER` varchar(32) DEFAULT NULL, `UPDATE_TIME` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(32) DEFAULT NULL,
  PRIMARY KEY (`ID`), KEY `IDX_ZJ_IMAGE_LISTING` (`LISTING_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='房源图片';

CREATE TABLE IF NOT EXISTS `ZJ_LISTING_EVIDENCE` (
  `ID` varchar(32) NOT NULL, `LISTING_ID` varchar(32) NOT NULL,
  `EVIDENCE_TYPE` varchar(32) NOT NULL, `FILE_URL` varchar(512) NOT NULL,
  `REVIEW_STATUS` varchar(32) NOT NULL DEFAULT 'PENDING_REVIEW',
  `REVIEW_REMARK` varchar(500) DEFAULT NULL,
  `DELETE_FLAG` varchar(32) DEFAULT NULL, `CREATE_TIME` datetime DEFAULT NULL,
  `CREATE_USER` varchar(32) DEFAULT NULL, `UPDATE_TIME` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(32) DEFAULT NULL,
  PRIMARY KEY (`ID`), KEY `IDX_ZJ_EVIDENCE_LISTING` (`LISTING_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='合同与租金证明';

CREATE TABLE IF NOT EXISTS `ZJ_FAVORITE` (
  `ID` varchar(32) NOT NULL, `USER_ID` varchar(32) NOT NULL, `LISTING_ID` varchar(32) NOT NULL,
  `DELETE_FLAG` varchar(32) DEFAULT NULL, `CREATE_TIME` datetime DEFAULT NULL,
  `CREATE_USER` varchar(32) DEFAULT NULL, `UPDATE_TIME` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(32) DEFAULT NULL,
  PRIMARY KEY (`ID`), UNIQUE KEY `UK_ZJ_FAVORITE_USER_LISTING` (`USER_ID`,`LISTING_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='房源收藏';

CREATE TABLE IF NOT EXISTS `ZJ_VIEWING_REQUEST` (
  `ID` varchar(32) NOT NULL, `LISTING_ID` varchar(32) NOT NULL, `REQUESTER_ID` varchar(32) NOT NULL,
  `PREFERRED_DATE` date NOT NULL, `PREFERRED_TIME` varchar(40) NOT NULL,
  `CONTACT_PHONE` varchar(32) NOT NULL, `MESSAGE` varchar(500) DEFAULT NULL,
  `STATUS` varchar(32) NOT NULL DEFAULT 'PENDING',
  `DELETE_FLAG` varchar(32) DEFAULT NULL, `CREATE_TIME` datetime DEFAULT NULL,
  `CREATE_USER` varchar(32) DEFAULT NULL, `UPDATE_TIME` datetime DEFAULT NULL,
  `UPDATE_USER` varchar(32) DEFAULT NULL,
  PRIMARY KEY (`ID`), KEY `IDX_ZJ_VIEWING_REQUESTER` (`REQUESTER_ID`),
  KEY `IDX_ZJ_VIEWING_LISTING` (`LISTING_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='看房预约';
